abbr bubu "brew update && brew outdated && brew upgrade && brew cleanup"
abbr cat "bat --plain --wrap character"
abbr fishcfg "nvim ~/.config/fish/config.fish"
abbr k "kubectl"
abbr l "eza -al"
abbr local_server "python3 -m http.server"
abbr vim "nvim"

abbr ga "git add"
abbr gaa "git add --all"
abbr gb "git branch"
abbr gbD "git branch --delete --force"
abbr gbd "git branch --delete"
abbr gc "git commit"
abbr gco "git checkout"
abbr gd "git diff"
abbr gl "git pull"
abbr glg "git log --stat"
abbr glog "git log --oneline --decorate --graph"
abbr gp "git push"
abbr gst "git status"
abbr gwch "git whatchanged -p --abbrev-commit --pretty=medium"
abbr gwtf 'git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"'
