abbr bubu "brew update && brew outdated && brew upgrade && brew cleanup"
abbr cat "bat --plain --wrap character"
abbr dgit "git --git-dir=$HOME/.local/share/dotfiles/ --work-tree=$HOME"
abbr fishcfg "nvim ~/.config/fish/config.fish"
abbr k "kubectl"
abbr l "eza -al"
abbr local_server "python3 -m http.server"
abbr vim "nvim"

abbr g "git"
abbr ga "git add"
abbr gaa "git add --all"
abbr gb "git branch"
abbr gbD "git branch --delete --force"
abbr gba "git branch -a"
abbr gbd "git branch --delete"
abbr gc "git commit -v"
abbr gc! "git commit -v --amend"
abbr gca "git commit -v -a"
abbr gca! "git commit -v -a --amend"
abbr gcam "git commit -a -m"
abbr gcas "git commit -a -s"
abbr gcasm "git commit -a -s -m"
abbr gcb "git checkout -b"
abbr gcf "git config --list"
abbr gclean "git clean -id"
abbr gco "git checkout"
abbr gcsm "git commit -s -m"
abbr gd "git diff"
abbr gds "git diff --staged"
abbr gfa "git fetch --all"
abbr gfo "git fetch origin"
abbr gl "git pull"
abbr glg "git log --stat"
abbr glog "git log --oneline --decorate --graph"
abbr gp "git push"
abbr gpristine "git reset --hard && git clean -dffx"
abbr gpu "git push upstream"
abbr gra "git remote add"
abbr grb "git rebase"
abbr grba "git rebase --abort"
abbr grbc "git rebase --continue"
abbr grbi "git rebase -i"
abbr grd 'git for-each-ref --format="%(refname:short)" refs/heads | xargs git branch -D'
abbr gsh "git show"
abbr gst "git status"
abbr gwch "git whatchanged -p --abbrev-commit --pretty=medium"
abbr gwtf 'git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"'

abbr ppr 'pulumi preview'
abbr pup 'pulumi up'
