
[[Snippets]]
  Description = "Check cert expiry"
  Filename = "/Users/elsesiy/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "echo | openssl s_client -connect <domain>:<port=443> 2> /dev/null | openssl x509 -dates -noout"
